### PR TITLE
Add yt embed

### PR DESCRIPTION
**Pull request by kimadactyl**

### CODE REVIEW

**Comment by WheresAlice** [comment]
I just get a spinning circle when I try and play the video now.  Does the embed only work once the stream is live?

**Comment by kimadactyl** [comment]
That would make sense yeah although it's a little confusing UX wise, I didn't actually try pressing play. I'm gonna try and put a pre-roll countdown card on if i get around to it. What do you think?

**Comment by WheresAlice** [comment]
A countdown card would be good - it gives people a minute or two to make sure the video is actually playing. And if we hit merge on this right at 5pm this should only take a few seconds to show up for any late-comers.

**Comment by kimadactyl** [comment]
hmmm i think its ok to merge now, it links to the vid, i think people are used to this kinda thing by now? main prob is right now the link is kinda hard to find as resistance lab doesnt have a sensible youtube url (you need 100 subs).

**Pull request merged**
